services:

  mongo:
    image : mongo
    container_name: eduquery-mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - eduquery-network


  backend:
    build : ./Backend 
    container_name: eduquery-backend
    env_file:
      - ./Backend/.env
    depends_on:
      - mongo
    networks:
      - eduquery-network

  frontend:
    build: ./Frontend
    container_name: eduquery-frontend
    networks:
      - eduquery-network

  nginx:
    image: nginx:alpine
    container_name: eduquery-nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - eduquery-network

volumes:
  mongo_data:

networks:
  eduquery-network:
    driver: bridge